//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugarCreek_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartRoundMapper
    {
        public System.Guid Id { get; set; }
        public System.Guid CartId { get; set; }
        public Nullable<System.Guid> RoundId { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
