//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugarCreek_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Golfer()
        {
            this.RoundMappers = new HashSet<RoundMapper>();
        }
    
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string GolfersName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundMapper> RoundMappers { get; set; }
    }
}
