//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugarCreek_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Round()
        {
            this.RoundMappers = new HashSet<RoundMapper>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TeeTimeId { get; set; }
        public Nullable<System.Guid> CartId { get; set; }
        public Nullable<int> NumberOfHoles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoundMapper> RoundMappers { get; set; }
        public virtual TeeTime TeeTime { get; set; }
    }
}
