//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugarCreek_DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SugarCreekEntities : DbContext
    {
        public SugarCreekEntities()
            : base("name=SugarCreekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CartRoundMapper> CartRoundMappers { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Golfer> Golfers { get; set; }
        public virtual DbSet<RoundMapper> RoundMappers { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<TeeTime> TeeTimes { get; set; }
    }
}
